# <font color="purple"><h3 align="center">DataFrame Basics Tutorial</h3></font>

## **Dataframe is most commonly used object in pandas. It is a table like datastructure containing rows and columns similar to excel spreadsheet**

In [51]:
import pandas as pd
weather_data = {
    'day': ['1/1/2017','1/2/2017','1/3/2017','1/4/2017','1/5/2017','1/6/2017'],
    'temperature': [32,35,28,24,32,31],
    'windspeed': [6,7,2,7,4,2],
    'event': ['Rain', 'Sunny', 'Snow','Snow','Rain', 'Sunny']
}
#df = pd.DataFrame(weather_data)
df = pd.read_csv("weather_data.csv")
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [52]:
df.shape # rows, columns = df.shape

(6, 4)

## <font color='blue'>Rows</font>

In [53]:
df.head(4) # df.head(3)

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow

In [54]:
df.tail(4) # df.tail(2)

        day  temperature  windspeed  event
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [55]:
df[4:6]

        day  temperature  windspeed  event
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

## <font color='blue'>Columns</font>

In [56]:
df.columns

Index(['day', 'temperature', 'windspeed', 'event'], dtype='object')

In [57]:
df['day'] # or df.day

0    1/1/2017
1    1/2/2017
2    1/3/2017
3    1/4/2017
4    1/5/2017
5    1/6/2017
Name: day, dtype: object

In [58]:
#see what's the type of a dataframe column, e.g 'day'
t = type(df['day'])
t

pandas.core.series.Series

In [59]:
#show day and temperature of dataframe
df['day'], df['temperature']

(0    1/1/2017
 1    1/2/2017
 2    1/3/2017
 3    1/4/2017
 4    1/5/2017
 5    1/6/2017
 Name: day, dtype: object,
 0    32
 1    35
 2    28
 3    24
 4    32
 5    31
 Name: temperature, dtype: int64)

## <font color='blue'>Operations On DataFrame</font>

In [60]:
df['temperature'].max()

35

In [61]:
df[df['temperature']>32]

        day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny

In [62]:
df['day'][df['temperature'] == df['temperature'].max()] # Kinda doing SQL in pandas

1    1/2/2017
Name: day, dtype: object

In [63]:
df[df['temperature'] == df['temperature'].max()] # Kinda doing SQL in pandas

        day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny

In [64]:
#Find standard deviation of temperature
df['temperature'].std()
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [65]:
df['temperature'].max() # But mean() won't work since data type is string

35

In [66]:
df.describe()  # use to describe statistical summary of data

       temperature  windspeed
count     6.000000   6.000000
mean     30.333333   4.666667
std       3.829708   2.338090
min      24.000000   2.000000
25%      28.750000   2.500000
50%      31.500000   5.000000
75%      32.000000   6.750000
max      35.000000   7.000000

**Google pandas series operations to find out list of all operations**
http://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.html

## <font color='blue'>set_index</font>

In [67]:
df.set_index('event')

            day  temperature  windspeed
event
Rain   1/1/2017           32          6
Sunny  1/2/2017           35          7
Snow   1/3/2017           28          2
Snow   1/4/2017           24          7
Rain   1/5/2017           32          4
Sunny  1/6/2017           31          2

In [68]:
df.set_index('event', inplace=True)

In [69]:
df.index

Index(['Rain', 'Sunny', 'Snow', 'Snow', 'Rain', 'Sunny'], dtype='object', name='event')

In [70]:
df

            day  temperature  windspeed
event
Rain   1/1/2017           32          6
Sunny  1/2/2017           35          7
Snow   1/3/2017           28          2
Snow   1/4/2017           24          7
Rain   1/5/2017           32          4
Sunny  1/6/2017           31          2

In [71]:
df.reset_index(inplace=True)
df.head()

   event       day  temperature  windspeed
0   Rain  1/1/2017           32          6
1  Sunny  1/2/2017           35          7
2   Snow  1/3/2017           28          2
3   Snow  1/4/2017           24          7
4   Rain  1/5/2017           32          4

In [72]:
df.set_index('event',inplace=True) # this is kind of building a hash map using event as a key
df

            day  temperature  windspeed
event
Rain   1/1/2017           32          6
Sunny  1/2/2017           35          7
Snow   1/3/2017           28          2
Snow   1/4/2017           24          7
Rain   1/5/2017           32          4
Sunny  1/6/2017           31          2

In [73]:
df.loc['Snow']

            day  temperature  windspeed
event
Snow   1/3/2017           28          2
Snow   1/4/2017           24          7

# <font color="purple"><h3 align="center">Pandas Concatenate Tutorial</h3></font>

## <font color='blue'>Basic Concatenation</font>

In [74]:
import pandas as pd

pakistani_weather = pd.DataFrame({
    "city": ["karachi","lahore","peshawar"],
    "temperature": [32,45,30],
    "humidity": [80, 60, 78]
})
pakistani_weather

       city  temperature  humidity
0   karachi           32        80
1    lahore           45        60
2  peshawar           30        78

In [75]:
us_weather = pd.DataFrame({
    "city": ["new york","chicago","orlando"],
    "temperature": [21,14,35],
    "humidity": [68, 65, 75]
})
us_weather

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [76]:
#concatinate us and pakistani weather
df = pd.concat([pakistani_weather, us_weather])
df

       city  temperature  humidity
0   karachi           32        80
1    lahore           45        60
2  peshawar           30        78
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

## <font color='blue'>Ignore Index</font>

In [77]:
df = pd.concat([pakistani_weather, us_weather], ignore_index=True)
df

       city  temperature  humidity
0   karachi           32        80
1    lahore           45        60
2  peshawar           30        78
3  new york           21        68
4   chicago           14        65
5   orlando           35        75

## <font color='blue'>Concatenation And Keys</font>

In [78]:
df = pd.concat([pakistani_weather, us_weather], keys=["pakistan", "us"])
df

                city  temperature  humidity
pakistan 0   karachi           32        80
         1    lahore           45        60
         2  peshawar           30        78
us       0  new york           21        68
         1   chicago           14        65
         2   orlando           35        75

In [79]:
#show city temperate and humidity of us cities
df.loc['us']

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [80]:
#show information of pakistani cities (city, temperature, humidity)
df.loc['pakistan']

       city  temperature  humidity
0   karachi           32        80
1    lahore           45        60
2  peshawar           30        78

## <font color='blue'>Concatenation Using Index</font>

In [81]:
temperature_df = pd.DataFrame({
    "city": ["karachi","lahore","peshawar"],
    "temperature": [32,45,30],
}, index=[0,1,2])
temperature_df

       city  temperature
0   karachi           32
1    lahore           45
2  peshawar           30

In [82]:
windspeed_df = pd.DataFrame({
    "city": ["lahore","karachi","peshawar"],
    "windspeed": [7,12,15],
}, index=[0,1,2])
windspeed_df

       city  windspeed
0    lahore          7
1   karachi         12
2  peshawar         15

In [83]:
#concatenate the temperature and windspeed of Lahore, Karachi and Peshawar
df = pd.concat([temperature_df,windspeed_df],axis=1)
df

       city  temperature      city  windspeed
0   karachi           32    lahore          7
1    lahore           45   karachi         12
2  peshawar           30  peshawar         15

## <font color='blue'>Concatenate dataframe with series</font>

In [84]:
s = pd.Series(["Humid","Dry","Rain"], name="event")
s

0    Humid
1      Dry
2     Rain
Name: event, dtype: object

In [85]:
df = pd.concat([temperature_df,s],axis=1)
df

       city  temperature  event
0   karachi           32  Humid
1    lahore           45    Dry
2  peshawar           30   Rain